name: Build/release

on: push

jobs:
  release:
    runs-on: windows-latest  # Only Windows runner

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM, and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Build/release Electron app for Windows
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          windows: true  # Only building for Windows
